import { MedusaService } from "@medusajs/framework/utils"
import Page from "./models/page"
import Blog from "./models/blog"

class CmsModuleService extends MedusaService({
  Page,
  Blog,
}) {
  // ✅ CRUD for Page & Blog is auto-generated by MedusaService:
  // createPages, updatePages, deletePages, listPages, retrievePage
  // createBlogs, updateBlogs, deleteBlogs, listBlogs, retrieveBlog

  // Add any custom methods below 👇

  async getPublishedPages() {
    return await this.listPages({ status: "published" })
  }

  async getPageBySlug(slug: string) {
    const [page] = await this.listPages({ slug })
    return page || null
  }

  async publishPage(id: string) {
    return await this.updatePages({ id, status: "published" })
  }
}

export default CmsModuleService