name: Deploy Medusa On Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DD_HOST }}
          username: ${{ secrets.DD_USER }}
          key: ${{ secrets.DD_SSH_KEY }}
          command_timeout: 30m
          
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            node -v
            npm -v
            cd /var/www/html/medusajs

            git pull origin main

            npm install

            npm run build

            pm2 restart medusajs
